In [2]:
import numpy

In [9]:
uninitializedArray = numpy.empty((4,3), numpy.float_)
print(uninitializedArray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
uninitializedArray = numpy.empty((4,3))
print(uninitializedArray.dtype)
print('Is by default double precision values ? ', uninitializedArray.dtype==numpy.float64)

float64
Is by default double precision values ?  True


In [11]:
z = numpy.zeros([3,3])
print(z)
print(z.dtype)
print('Is by default double precision values ? ', z.dtype==numpy.float64)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
Is by default double precision values ?  True


In [12]:
o = numpy.ones((2,3))
print(o)
print(o.dtype)
print('Is by default double precision values ? ', o.dtype==numpy.float64)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
Is by default double precision values ?  True


In [16]:
c = numpy.ones((2,3), dtype=[('hour',numpy.int_),('minute',numpy.int_)])
print(c)
print(c.dtype)
print(c.dtype==[('hour',numpy.int_),('minute',numpy.int_)])

[[(1, 1) (1, 1) (1, 1)]
 [(1, 1) (1, 1) (1, 1)]]
[('hour', '<i8'), ('minute', '<i8')]
True


In [23]:
array = numpy.asarray([1, 2, 3])
print(array)
print(array.dtype)

[1 2 3]
int64


In [24]:
array = numpy.asarray([1, 2, 3], dtype=numpy.float_)
print(array)
print(array.dtype)

[1. 2. 3.]
float64


In [29]:
array = numpy.asarray([(1,1), (2,3), (5,4)], dtype=numpy.float_)
print(array)
print(array.dtype)

[[1. 1.]
 [2. 3.]
 [5. 4.]]
float64


In [31]:
array = numpy.asarray([(1,1,4), (2,3), (5,4)])
print(array)
print(array.dtype)

[(1, 1, 4) (2, 3) (5, 4)]
object


In [37]:
array = numpy.array([(1,1,4), (2,3), (5,4)], dtype=numpy.float_)
print(array)
print(array.dtype)

ValueError: setting an array element with a sequence.

In [46]:
setA = {1.4, -2.7, 3}
iterator = iter(setA)
array = numpy.asarray(setA)
print(array)
print(array.dtype)
array = numpy.asarray(setA, dtype=numpy.float_)

{1.4, 3, -2.7}
object


TypeError: float() argument must be a string or a number, not 'set'

In [44]:
setA = {1.4, -2.7, 3}
iterator = iter(setA)
array = numpy.fromiter(iterator, dtype=numpy.float_)
print(array)

[ 1.4  3.  -2.7]


In [8]:
uninitializedArray = numpy.empty((4,3), numpy.float_)
print(uninitializedArray)
zerosArray = numpy.zeros_like(uninitializedArray)
print(zerosArray)
onesArray = numpy.ones_like(uninitializedArray)
print(onesArray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
