In [55]:
import numpy

In [56]:
array = numpy.random.rand(4,5)
print(array, '\n')
print(array[[1,2,0], [3,4,2]])

[[0.92845352 0.16938755 0.82839833 0.15504204 0.49611233]
 [0.27286495 0.74974838 0.60870984 0.40007035 0.64929246]
 [0.15948101 0.78485431 0.34317342 0.66937784 0.32755384]
 [0.62122364 0.33721088 0.02496979 0.56059521 0.68150808]] 

[0.40007035 0.32755384 0.82839833]


In [57]:
array = numpy.random.rand(5,5)
print(array, '\n')
print(array[0:5:2,0:5:2])

[[0.27521959 0.27861057 0.58297759 0.44583877 0.28807746]
 [0.34750637 0.66642227 0.80867967 0.56621334 0.35838841]
 [0.75531196 0.79968002 0.9084849  0.2111054  0.23396348]
 [0.63656177 0.24238441 0.53381965 0.38665224 0.07821964]
 [0.2061978  0.10815649 0.02311696 0.79217029 0.6970535 ]] 

[[0.27521959 0.58297759 0.28807746]
 [0.75531196 0.9084849  0.23396348]
 [0.2061978  0.02311696 0.6970535 ]]


In [58]:
array = numpy.array([
        [0,  1,  2],
        [3,  4,  5],
        [6,  7,  8],
        [9, 10, 11]
    ],
    dtype=numpy.float_
)
print(array)
rows = numpy.array([1]) ; columns = numpy.array([2]) ; print(array[rows, columns])
rows = numpy.array([1, 3]) ; columns = numpy.array([2]) ; print(array[rows, columns])
rows = numpy.array([[1], [3]]) ; columns = numpy.array([2]) ; print(array[rows, columns])
rows = numpy.array([1, 3]) ; columns = numpy.array([2,1]) ; print(array[rows, columns])
rows = numpy.array([1]) ; columns = numpy.array([2,1]) ; print(array[rows, columns])
rows = numpy.array([1]) ; columns = numpy.array([[2],[1]]) ; print(array[rows, columns])

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[5.]
[ 5. 11.]
[[ 5.]
 [11.]]
[ 5. 10.]
[5. 4.]
[[5.]
 [4.]]


In [59]:
array = numpy.array([
        [0,  1,  2],
        [3,  4,  5],
        [6,  7,  8],
        [9, 10, 11]
    ],
    dtype=numpy.float_
)
print(array, '\n')
print(array[:,[0,2]], '\n')
print(array[1:3,[0,2]], '\n')

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] 

[[ 0.  2.]
 [ 3.  5.]
 [ 6.  8.]
 [ 9. 11.]] 

[[3. 5.]
 [6. 8.]] 



In [60]:
array = numpy.array([
        [0,  1,  2],
        [3,  4,  5],
        [6,  7,  8],
        [9, 10, 11]
    ],
    dtype=numpy.float_
)
print(array, '\n')
print(array>3)
print(array[array>3])

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] 

[[False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 4.  5.  6.  7.  8.  9. 10. 11.]


In [61]:
array = numpy.array([
        [0,  1,  2],
        [3,  4,  5],
        [6,  7,  8],
        [9, 10, 11]
    ],
    dtype=numpy.float_
)
print(array, '\n')
print(array==5)
print(array[array==5])
# It can be used to select specific values

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] 

[[False False False]
 [False False  True]
 [False False False]
 [False False False]]
[5.]


In [62]:
array = numpy.array([numpy.nan, 1, 2, numpy.nan, 3, 4, 5]) 
print(~numpy.isnan(array))
print(array[~numpy.isnan(array)])
# It can be used to filter values!

[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]
