In [19]:
import numpy

In [20]:
rangeArray = numpy.arange(5)
print(rangeArray)
print(rangeArray.dtype)

rangeArray = numpy.arange(5.)
print(rangeArray)
print(rangeArray.dtype)

[0 1 2 3 4]
int64
[0. 1. 2. 3. 4.]
float64


In [21]:
rangeArray = numpy.arange(-3, 5, 0.83, dtype=numpy.float_)
print(rangeArray)

[-3.   -2.17 -1.34 -0.51  0.32  1.15  1.98  2.81  3.64  4.47]


In [22]:
rangeArray = numpy.arange(numpy.complex(0,0), numpy.complex(4,3), numpy.complex(1,0), dtype=numpy.complex)
print(rangeArray)
rangeArray = numpy.arange(numpy.complex(0,0), numpy.complex(0, 5), numpy.complex(0,1), dtype=numpy.complex)
print(rangeArray)
rangeArray = numpy.arange(0, 5, 1) * numpy.complex(0,1)
print(rangeArray)

[0.+0.j 1.+0.j 2.+0.j]
[]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [25]:
linearSpaced = numpy.linspace(5, 10, 6)
print(linearSpaced)
print(linearSpaced.dtype)

[ 5.  6.  7.  8.  9. 10.]
float64


In [26]:
linearSpaced = numpy.linspace(5, 10, 4)
print(linearSpaced)
print(linearSpaced.dtype)

[ 5.          6.66666667  8.33333333 10.        ]
float64


In [28]:
linearSpaced, step = numpy.linspace(7, 12, 9, retstep=True)
print(linearSpaced)
print(linearSpaced[1] - linearSpaced[0])
print(step)

[ 7.     7.625  8.25   8.875  9.5   10.125 10.75  11.375 12.   ]
0.625
0.625


In [29]:
logSpaced = numpy.logspace(0, 3, 6, base=3)
print(logSpaced)

[ 1.          1.93318204  3.73719282  7.22467406 13.96661017 27.        ]
