In [2]:
import numpy

In [4]:
arrayA = numpy.arange(9).reshape(3,3)
arrayB = numpy.arange(10,40,10)
print(arrayA, '\n')
print(arrayB, '\n')
print(arrayA + arrayB, '\n')
print(arrayA - arrayB, '\n')
print(arrayA * arrayB, '\n')
print(arrayA / arrayB, '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[10 20 30] 

[[10 21 32]
 [13 24 35]
 [16 27 38]] 

[[-10 -19 -28]
 [ -7 -16 -25]
 [ -4 -13 -22]] 

[[  0  20  60]
 [ 30  80 150]
 [ 60 140 240]] 

[[0.         0.05       0.06666667]
 [0.3        0.2        0.16666667]
 [0.6        0.35       0.26666667]] 



In [8]:
array = numpy.arange(1.,10.).reshape(3,3)
print(1/array, '\n')
print(numpy.reciprocal(array), '\n')

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]] 



In [10]:
array = numpy.arange(1.,10.).reshape(3,3)
print(numpy.power(2,array), '\n')
print(2**array, '\n')
print(numpy.power(array,2), '\n')
print(array**2, '\n')

[[  2.   4.   8.]
 [ 16.  32.  64.]
 [128. 256. 512.]] 

[[  2.   4.   8.]
 [ 16.  32.  64.]
 [128. 256. 512.]] 

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]] 

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]] 



In [20]:
print( 21%10 )
print( numpy.mod(21, 10) )
print( numpy.mod([11,14,17], 4) )
print( numpy.remainder([11,14,17], 4) )
print( numpy.array([11,14,17])%4 )
print( numpy.mod([11,14,17], [4,3,5]) )

1
1
[3 2 1]
[3 2 1]
[3 2 1]
[3 2 2]


In [29]:
cplx = numpy.complex(3,4)
print(cplx)
print(numpy.real(cplx))
print(numpy.imag(cplx))
print(numpy.conj(cplx))
print(numpy.angle(cplx), '==', numpy.degrees(numpy.angle(cplx)), 'degree')
print(numpy.abs(cplx))

(3+4j)
3.0
4.0
(3-4j)
0.9272952180016122 == 53.13010235415598 degree
5.0


In [32]:
arrayA = numpy.arange(1.,10.).reshape(3,3)
arrayB = numpy.arange(-1.,-10.,-1).reshape(3,3)
print(arrayA, '\n')
print(arrayB, '\n')
print(arrayA + arrayB, '\n')
print(arrayA - arrayB, '\n')
print(arrayA * arrayB, '\n')
print(arrayA / arrayB, '\n')

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

[[ -1.  -4.  -9.]
 [-16. -25. -36.]
 [-49. -64. -81.]] 

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]] 

