In [2]:
import numpy
import os

In [61]:
array = numpy.random.rand(4)
print('Original array:\n', array)
fileName = 'testArray.npy'
numpy.save(fileName, array)
print('\nWas the file "{:s}" created? {:b}'.format(fileName, fileName in os.listdir()))

readArray = numpy.load(fileName)
print('\nRead array:\n', readArray)
print('Is the read array equal to the original? {:b}'.format(numpy.array_equal(array,readArray)))

os.remove(fileName)

Original array:
 [0.8517455  0.47775108 0.23421006 0.54754967]

Was the file "testArray.npy" created? 1

Read array:
 [0.8517455  0.47775108 0.23421006 0.54754967]
Is the read array equal to the original? 1


In [62]:
array = numpy.random.rand(3,3)
print('Original array:\n', array)
fileName = 'testArray.txt'
numpy.savetxt(fileName, array, delimiter=', ', newline='\n',
              header='array to test the numpy.savetxt function', footer='end of array')
print('\nWas the file "{:s}" created? {:b}'.format(fileName, fileName in os.listdir()))

print('\nFile "{:s}" content:', fileName)
file = open(fileName)
for line in file.readlines():
    print(line, end='')
file.close()

readArray = numpy.loadtxt(fileName, delimiter=',')
print('\nRead array:\n', readArray)
print('Is the read array equal to the original? {:b}'.format(numpy.array_equal(array,readArray)))

os.remove(fileName)

Original array:
 [[0.60205828 0.59687289 0.34468637]
 [0.38590846 0.4043072  0.52143485]
 [0.1610047  0.91887056 0.31783345]]

Was the file "testArray.txt" created? 1

File "{:s}" content: testArray.txt
# array to test the numpy.savetxt function
6.020582843893851344e-01, 5.968728927472392032e-01, 3.446863746617141455e-01
3.859084634548499704e-01, 4.043072035391076513e-01, 5.214348465249616371e-01
1.610047019833473758e-01, 9.188705626546617156e-01, 3.178334544800545114e-01
# end of array

Read array:
 [[0.60205828 0.59687289 0.34468637]
 [0.38590846 0.4043072  0.52143485]
 [0.1610047  0.91887056 0.31783345]]
Is the read array equal to the original? 1


In [63]:
array0 = numpy.random.rand(2,2)
array1 = numpy.random.rand(2,2)

print('\n', array0)
print('\n', array1)

fileName = 'testArray.npz'
numpy.savez(fileName, array0=array0, array1=array1)

readArray = numpy.load(fileName)
print('\nRead data:\n', readArray)
print('\nRead data:\n', readArray.files)
print('\n', readArray['array0'])
print('\n', readArray['array1'])

os.remove(fileName)


 [[0.59373186 0.83299347]
 [0.15636601 0.87163301]]

 [[0.95064056 0.85441308]
 [0.1629191  0.47639987]]

Read data:

Read data:
 ['array0', 'array1']

 [[0.59373186 0.83299347]
 [0.15636601 0.87163301]]

 [[0.95064056 0.85441308]
 [0.1629191  0.47639987]]


In [ ]:
size = 100
array0 = numpy.random.rand(size,size)
array1 = numpy.random.rand(size,size)

uncompressed = 'uncompressed_array.npz'
compressed = 'compressed_array.npz'
numpy.savez(uncompressed, array0=array0, array1=array1)
numpy.savez_compressed(compressed, array0=array0, array1=array1)

print('Uncompressed file size: {:d}'.format(os.stat(uncompressed).st_size))
print('Uncompressed file size: {:d}'.format(os.stat(compressed).st_size))

os.remove(uncompressed)
os.remove(compressed)