In [1]:
import numpy

In [2]:
array = numpy.array([1, 2, 3]); print(array)
array = array*array; print(array)

[1 2 3]
[1 4 9]


In [3]:
bigArray = numpy.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
smallArray = numpy.array([500, 600, 700])
print(bigArray)
print(smallArray)
print(bigArray + smallArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[500 600 700]
[[501 602 703]
 [504 605 706]
 [507 608 709]]


In [7]:
bigArray = numpy.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
smallArray = numpy.array([[500], [600], [700]])
print(bigArray)
print(smallArray)
print(bigArray + smallArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[500]
 [600]
 [700]]
[[501 502 503]
 [604 605 606]
 [707 708 709]]


In [5]:
array = numpy.array([
        [10, 20, 30],
        [100, 200, 300]
    ])
value = 1
list = [1]
print(array)
print(value)
print(array+value)
print(array+list)

[[ 10  20  30]
 [100 200 300]]
1
[[ 11  21  31]
 [101 201 301]]
[[ 11  21  31]
 [101 201 301]]


In [6]:
array = numpy.array([
        [10, 20, 30],
        [100, 200, 300]
    ])
wrongArray = numpy.array([
        [1, 2]
    ])
print(array)
print(wrongArray)
print(array + wrongArray)

[[ 10  20  30]
 [100 200 300]]
[[1 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 