In [2]:
import numpy

In [9]:
array = numpy.arange(4).reshape(2,2)
arrayView = array.view()

print(array)
print(arrayView, '\n')

print(id(array))
print(id(arrayView), '\n')

# I can change the array object properties
# not related to its data without changing
# the original object.
arrayView.shape = (4,1)
print(array)
print(arrayView, '\n')

# However, the data content are shared.
arrayView[0,0] = 10
print(array)
print(arrayView, '\n')

[[0 1]
 [2 3]]
[[0 1]
 [2 3]] 

140665891666960
140665891666480 

[[0 1]
 [2 3]]
[[0]
 [1]
 [2]
 [3]] 

[[10  1]
 [ 2  3]]
[[10]
 [ 1]
 [ 2]
 [ 3]] 



In [10]:
array = numpy.arange(4).reshape(2,2)
arrayCopy = array.copy()

print(array)
print(arrayCopy, '\n')

print(id(array))
print(id(arrayCopy), '\n')

arrayCopy.shape = (4,1)
print(array)
print(arrayCopy, '\n')

arrayCopy[0,0] = 10
print(array)
print(arrayCopy, '\n')

[[0 1]
 [2 3]]
[[0 1]
 [2 3]] 

140665891666400
140665891666960 

[[0 1]
 [2 3]]
[[0]
 [1]
 [2]
 [3]] 

[[0 1]
 [2 3]]
[[10]
 [ 1]
 [ 2]
 [ 3]] 

