In [5]:
import numpy

In [45]:
# numpy matrix is a numpy array
# but with especifically two dimensions.

In [46]:
print(numpy.empty((2,2)), '\n')
print(numpy.zeros((3,3)), '\n')
print(numpy.ones((4,4)), '\n')
print(numpy.identity(4), '\n')
for k in numpy.arange(-3,4):
    print('diagonal ', k, '\n', numpy.eye(3,3,k), '\n')
for k in numpy.arange(-1,2):
    print('diagonal ', k, '\n', numpy.diagflat([3,-4],k), '\n')
print(numpy.random.rand(3,3), '\n')
print(numpy.random.rand(2,2,2))

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

diagonal  -3 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

diagonal  -2 
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]] 

diagonal  -1 
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]] 

diagonal  0 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

diagonal  1 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]] 

diagonal  2 
 [[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] 

diagonal  3 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

diagonal  -1 
 [[ 0  0  0]
 [ 3  0  0]
 [ 0 -4  0]] 

diagonal  0 
 [[ 3  0]
 [ 0 -4]] 

diagonal  1 
 [[ 0  3  0]
 [ 0  0 -4]
 [ 0  0  0]] 

[[0.504619   0.28359743 0.81637796]
 [0.17976414 0.89354335 0.12459048]
 [0.94234596 0.25428737 0.62156279]] 

[[[0.52855019 0.23419142]
  [0.15427045 0.10996637]]

 [[0.09226273 0.04614502]
  [0.77270102 0.65442447]]]


In [47]:
a = numpy.array([
        [1, 2],
        [3, 4]
    ])
b = numpy.array([
        [1, 2],
        [3, 4]
    ])
print(a, '\n')
print(b, '\n')
print(numpy.dot(a, b), '\n')
print(a @ b, '\n')
print(numpy.matmul(a,b), '\n')

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]] 

[[ 7 10]
 [15 22]] 

[[ 7 10]
 [15 22]] 

[[ 7 10]
 [15 22]] 



In [48]:
matrix = numpy.array([
        [1, 2],
        [3, 4]
    ])
columnMatrix = numpy.array([
        [5],
        [6]
    ])
array = numpy.array([
        5, 6
    ])
lineMatrix = numpy.array([
        [5,6]
    ])

print('matmul function')
print(numpy.matmul(matrix,columnMatrix), '\n')
print(numpy.matmul(matrix,array), '\n')
# print(numpy.matmul(columnMatrix,matrix), '\n') # dimension error
print(numpy.matmul(array,matrix), '\n')
# print(numpy.matmul(matrix,lineMatrix), '\n') # dimension error
print(numpy.matmul(lineMatrix,matrix), '\n')

print('dot function')
print(numpy.dot(matrix,columnMatrix), '\n')
print(numpy.dot(matrix,array), '\n')
# print(numpy.dot(columnMatrix,matrix), '\n') # dimension error
print(numpy.dot(array,matrix), '\n')
# print(numpy.dot(matrix,lineMatrix), '\n') # dimension error
print(numpy.dot(lineMatrix,matrix), '\n')

print('@ function')
print(matrix@columnMatrix, '\n')
print(matrix@array, '\n')
# print(columnMatrix@matrix, '\n') # dimension error
print(array@matrix, '\n')
# print(matrix@lineMatrix, '\n') # dimension error
print(lineMatrix@matrix, '\n')

matmul function
[[17]
 [39]] 

[17 39] 

[23 34] 

[[23 34]] 

dot function
[[17]
 [39]] 

[17 39] 

[23 34] 

[[23 34]] 

@ function
[[17]
 [39]] 

[17 39] 

[23 34] 

[[23 34]] 



In [49]:
vecA = numpy.array([[1, 2]])
vecB = numpy.array([[1, 2]])
arrayA = numpy.array([1, 2])
arrayB = numpy.array([1, 2])

print('vector * vector:')
# print(numpy.dot(vecA,vecB)) # dimension error
# print(numpy.matmul(vecA,vecB)) # dimension error
# print(vecA@vecB) # dimension error

print('array * vector:')
print(numpy.dot(vecA,arrayB))
print(numpy.matmul(vecA,arrayB))
print(vecA@arrayB)

print('array * array:')
print(numpy.dot(arrayA,arrayB))
print(numpy.matmul(arrayA,arrayB))
print(arrayA@arrayB)

vector * vector:
array * vector:
[5]
[5]
[5]
array * array:
5
5
5


In [44]:
# For determinant, decomposition,
# linear solver, least squares,
# linear solver, see scipy.linalg
# package