In [1]:
import numpy

In [10]:
array0 = numpy.array([range(5,11), range(-5,-11,-1)], dtype=numpy.float64)
print(array0)

[[  5.   6.   7.   8.   9.  10.]
 [ -5.  -6.  -7.  -8.  -9. -10.]]


In [13]:
array1 = numpy.array([
        [numpy.complex(3,4), numpy.complex(-5,8.5)],
        [numpy.complex(6.2,-9.1), numpy.complex(0,2)]],
        dtype=numpy.complex_)
print(array1)

[[ 3. +4.j  -5. +8.5j]
 [ 6.2-9.1j  0. +2.j ]]


In [37]:
dataType = numpy.dtype(">f8", True, True)
array2 = numpy.array([1, 2, 3], dtype = dataType)
print(array2.dtype)
print(array2)

>f8
[1. 2. 3.]


In [52]:
dataType = numpy.dtype([("hour", numpy.int_), ("minute", numpy.int_)])
print(dataType)
array3 = numpy.array([
        [(12,7), (9,18)],
        [(8,14), (5,21)]],
    dtype=dataType)
print("\nhours and minutes:\n", array3)
print("\nhours:\n", array3["hour"])
print("\nminutes:\n", array3["minute"])

[('hour', '<i8'), ('minute', '<i8')]

hours and minutes:
 [[(12,  7) ( 9, 18)]
 [( 8, 14) ( 5, 21)]]

hours:
 [[12  9]
 [ 8  5]]

minutes:
 [[ 7 18]
 [14 21]]


In [56]:
array4 = numpy.array([
        [5, -2, 9.4],
        [7, 4, 2.6]])
print(array4)
print("\narray4 shape: ", array4.shape)
array4.shape = (3,2)
print("\narray4 reshaped:\n", array4)

[[ 5.  -2.   9.4]
 [ 7.   4.   2.6]]

array4 shape:  (2, 3)

array4 reshaped:
 [[ 5.  -2. ]
 [ 9.4  7. ]
 [ 4.   2.6]]


In [64]:
T = numpy.array(
    [
        1, 2, 3, 1, 2, 3, 1, 2, 3
    ])
print(T.ndim)
print(T)
print("\n")
T = T.reshape(3,3)
print(T.ndim)
print(T.itemsize)
print(T.dtype)
print(T)

1
[1 2 3 1 2 3 1 2 3]


2
8
int64
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
array5 = numpy.array(
    [
        [1, 2, 3],
        [1, 2, 3]
    ],
    dtype=numpy.float_)
print("\noriginal:\n", array5)
array5[0,0] = 7
print("\nmodified:\n", array5)
array5.flags.writeable = False
array5[0,0] = 14


original:
 [[1. 2. 3.]
 [1. 2. 3.]]

modified:
 [[7. 2. 3.]
 [1. 2. 3.]]


ValueError: assignment destination is read-only