In [1]:
import numpy

In [10]:
array = numpy.arange(1,4)
print('Original:\n', array)
print(array.shape)
array = numpy.broadcast_to(array,(3,3))
print('\nBroadcasted:\n', array)
print(array.shape)

Original:
 [1 2 3]
(3,)

Broadcasted:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [27]:
array = numpy.arange(9).reshape(3,3)
print(array)
print()
for val in array.flat:
    print(val, ', ', end='')
print('\n')
flatted = array.flatten()
print(flatted, ' ; ', flatted.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 

[0 1 2 3 4 5 6 7 8]  ;  (9,)

id(flatted[0]) == id(array[0]) ?  False


In [28]:
array = numpy.arange(9).reshape(3,3)
print(array)
print()
for val in array.flat:
    print(val, ', ', end='')
print('\n')
flatted = array.ravel()
print(flatted, ' ; ', flatted.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 

[0 1 2 3 4 5 6 7 8]  ;  (9,)

id(flatted[0]) == id(array[0]) ?  False


In [38]:
array = numpy.arange(9).reshape(3,3)
print(array, '\n')
print(numpy.transpose(array, (1,0)), '\n') #'x'=='0' becomes 'y'=='1' and vice-versa
print(numpy.transpose(array), '\n')
print(array.T, '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 



In [44]:
array = numpy.arange(9)
print(array, '\n')
array = numpy.expand_dims(array, 1)
print(array, '\n')
array = numpy.squeeze(array, 1)
print(array)

[0 1 2 3 4 5 6 7 8] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

[0 1 2 3 4 5 6 7 8]


In [53]:
arrayA = numpy.array([
        [1, 2],
        [3, 4]
    ])
arrayB = numpy.array([
        [5, 6],
        [7, 8]
    ])
print('\nA:\n', arrayA)
print('\nB:\n', arrayB)
print('\ncat((A,B)):\n', numpy.concatenate((arrayA,arrayB)))
print('\ncat((A,B), 0):\n', numpy.concatenate((arrayA,arrayB), 0))
print('\ncat((A,B), 1):\n', numpy.concatenate((arrayA,arrayB), 1))


A:
 [[1 2]
 [3 4]]

B:
 [[5 6]
 [7 8]]

cat((A,B)):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

cat((A,B), 0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

cat((A,B), 1):
 [[1 2 5 6]
 [3 4 7 8]]


In [54]:
arrayA = numpy.arange(0,3)
arrayB = numpy.arange(3,6)
print('\nA:\n', arrayA)
print('\nB:\n', arrayB)
print('\nstack((A,B)):\n', numpy.stack( (arrayA,arrayB) ))
print('\nstack((A,B), 0):\n', numpy.stack( (arrayA,arrayB) , 0))
print('\nhstack((A,B), 0):\n', numpy.hstack( (arrayA,arrayB) ))
print('\nstack((A,B), 1):\n', numpy.stack( (arrayA,arrayB) , 1))
print('\nstack((A,B), 1):\n', numpy.vstack( (arrayA,arrayB) ))


A:
 [0 1 2]

B:
 [3 4 5]

stack((A,B)):
 [[0 1 2]
 [3 4 5]]

stack((A,B), 0):
 [[0 1 2]
 [3 4 5]]

hstack((A,B), 0):
 [0 1 2 3 4 5]

stack((A,B), 1):
 [[0 3]
 [1 4]
 [2 5]]

stack((A,B), 1):
 [[0 1 2]
 [3 4 5]]


In [56]:
array = numpy.arange(10)
print(array)
print(numpy.array_split(array,3)) # Not equal divisions (almost equal), but works
print(numpy.split(array,3)) # Must be equally divided

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


ValueError: array split does not result in an equal division

In [61]:
array = numpy.arange(10)
print(array)
print([1, 4, 6], ' split: ', numpy.split(array,[1, 4, 6]))

[0 1 2 3 4 5 6 7 8 9]
[1, 4, 6]  split:  [array([0]), array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [65]:
array = numpy.identity(5)
print(array)
for vector in numpy.split(array,5,axis=1):
    print('\n', vector)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

 [[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]]

 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

 [[0.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [66]:
array = numpy.identity(3)
print(array)
print(array.resize(4,4))
print(array.reshape(4,4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
None
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [71]:
array = numpy.arange(9).reshape(3,3)
toInsert = numpy.arange(9,9+3)
print(array, '\n')
print(toInsert, '\n')
print(numpy.insert(array,2,toInsert), '\n')
print(numpy.insert(array,2,toInsert,axis=0), '\n')
print(numpy.insert(array,2,toInsert,axis=1), '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[ 9 10 11] 

[ 0  1  9 10 11  2  3  4  5  6  7  8] 

[[ 0  1  2]
 [ 3  4  5]
 [ 9 10 11]
 [ 6  7  8]] 

[[ 0  1  9  2]
 [ 3  4 10  5]
 [ 6  7 11  8]] 



In [83]:
array = numpy.arange(4*4).reshape(4,4)
print(array, '\n')
print(numpy.delete(array,2), '\n')
print(numpy.delete(array,2,axis=0), '\n')
print(numpy.delete(array,2,axis=1), '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]] 

[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]
 [12 13 15]] 



In [82]:
array = numpy.arange(4*4).reshape(4,4)
print(array, '\n')
print(numpy.delete(array, (slice(1,3),slice(1,3)) ) , '\n')
    # I'd like to remove a specific block, but
    # I don't know how to do it.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



/usr/lib/python3/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  This is separate from the ipykernel package so we can avoid doing imports until


TypeError: int() argument must be a string, a bytes-like object or a number, not 'slice'