In [1]:
import numpy

In [9]:
array = numpy.arange(9)
array = 2**array
array = array.reshape(3,3)
print('array:\n', array)
print('\nUsing iterator:')
for val in numpy.nditer(array):
    print(val, end=', ')
    
array = numpy.transpose(array)
print('\n\nTransposed array:\n', array)
print('\nIterators consider the way the data is stored in memory:')
for val in numpy.nditer(array):
    print(val, end=', ')

array:
 [[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]

Using iterator:
1, 2, 4, 8, 16, 32, 64, 128, 256, 

Transposed array:
 [[  1   8  64]
 [  2  16 128]
 [  4  32 256]]

Iterators consider the way the data is stored in memory:
1, 2, 4, 8, 16, 32, 64, 128, 256, 

In [31]:
array = numpy.arange(9.)
array = 2**array
array = array.reshape(3,3)
print(array)
for val in numpy.nditer(array,op_flags=['readwrite']):
    val[...] = 4 # don't ask me why the ellipse makes it works...
print(array)

[[  1.   2.   4.]
 [  8.  16.  32.]
 [ 64. 128. 256.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [32]:
array = numpy.arange(9.)
array = 2**array
array = array.reshape(3,3)
print(array)
for val in numpy.nditer(array,op_flags=['readonly']):
    val[...] = 4 # don't ask me why the ellipse makes it works...
print(array)

[[  1.   2.   4.]
 [  8.  16.  32.]
 [ 64. 128. 256.]]


ValueError: assignment destination is read-only

In [40]:
# it is possible iterate by groups
array = numpy.arange(9.)
array = 2**array
array = array.reshape(3,3)

print(array)

for val in numpy.nditer(array, flags=['external_loop'], order='F'):
    print(val, type(val), val.shape)

for val in numpy.nditer(array, flags=['external_loop']): # order='C'
    print(val, type(val), val.shape)

[[  1.   2.   4.]
 [  8.  16.  32.]
 [ 64. 128. 256.]]
[ 1.  8. 64.] <class 'numpy.ndarray'> (3,)
[  2.  16. 128.] <class 'numpy.ndarray'> (3,)
[  4.  32. 256.] <class 'numpy.ndarray'> (3,)
[  1.   2.   4.   8.  16.  32.  64. 128. 256.] <class 'numpy.ndarray'> (9,)


In [48]:
arrayA = numpy.arange(9.)
arrayA = 2**arrayA
arrayA = arrayA.reshape(3,3)

arrayB = numpy.arange(3.)

print('A:\n', arrayA)
print('B:\n', arrayB)

print('\nA        B')
for valA, valB in numpy.nditer([arrayA, arrayB]):
    print(valA, ' , ', valB)

A:
 [[  1.   2.   4.]
 [  8.  16.  32.]
 [ 64. 128. 256.]]
B:
 [0. 1. 2.]

A        B
1.0  ,  0.0
2.0  ,  1.0
4.0  ,  2.0
8.0  ,  0.0
16.0  ,  1.0
32.0  ,  2.0
64.0  ,  0.0
128.0  ,  1.0
256.0  ,  2.0
