In [1]:
import numpy

In [27]:
# slice syntax
array = numpy.arange(0,12,1); print(array)
s = slice(1,7,2); print(array[s])
s = slice(3); print(array[s])
s = slice(2,-1); print(array[s])
s = slice(-5,-2); print(array[s])
s = slice(7,10); print(array[s])
s = slice(-1,0,-1); print(array[s])
s = slice(-1,None,-1); print(array[s])
s = slice(None); print(array[s])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 3 5]
[0 1 2]
[ 2  3  4  5  6  7  8  9 10]
[7 8 9]
[7 8 9]
[11 10  9  8  7  6  5  4  3  2  1]
[11 10  9  8  7  6  5  4  3  2  1  0]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
array = numpy.arange(10)
s = reversed(slice(None)); print(array[s])

TypeError: 'slice' object is not reversible

In [25]:
array = numpy.arange(10)
s = (1:7:2); print(array(s))

SyntaxError: invalid syntax (<ipython-input-25-7da247cb8442>, line 2)

In [29]:
# slice syntax
array = numpy.arange(0,12,1); print(array)
print(array[1:7:2])
print(array[:3])
print(array[2:-1])
print(array[-5:-2])
print(array[7:10])
print(array[-1:0:-1])
print(array[-1:None:-1])
print(array[None])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 3 5]
[0 1 2]
[ 2  3  4  5  6  7  8  9 10]
[7 8 9]
[7 8 9]
[11 10  9  8  7  6  5  4  3  2  1]
[11 10  9  8  7  6  5  4  3  2  1  0]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [68]:
def arrayInfo(array):
    print(array, type(array), array.shape, '\n')

array0 = numpy.transpose([numpy.arange(1.,5.)]); arrayInfo(array0)
array1 = numpy.array([numpy.arange(1.,5.)]); arrayInfo(array1)
array = numpy.array(
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]); arrayInfo(array)
arrayInfo(array[0,2])
arrayInfo(array[:,2])
arrayInfo(array[...,2])
arrayInfo(array[1,:])
arrayInfo(array[1,...])
arrayInfo(array[0:1,0:1])
arrayInfo(array[0:2,0:2])
l = [slice(0,2), slice(0,2)]; arrayInfo(array[l])
arrayInfo(array[...,:])
arrayInfo(array[:,...])
arrayInfo(array[:,:])

[[1.]
 [2.]
 [3.]
 [4.]] <class 'numpy.ndarray'> (4, 1) 

[[1. 2. 3. 4.]] <class 'numpy.ndarray'> (1, 4) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'> (3, 3) 

2 <class 'numpy.int64'> () 

[2 5 8] <class 'numpy.ndarray'> (3,) 

[2 5 8] <class 'numpy.ndarray'> (3,) 

[3 4 5] <class 'numpy.ndarray'> (3,) 

[3 4 5] <class 'numpy.ndarray'> (3,) 

[[0]] <class 'numpy.ndarray'> (1, 1) 

[[0 1]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 

[[0 1]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'> (3, 3) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'> (3, 3) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'> (3, 3) 

