In [12]:
import pandas as pd
import numpy as np
import os
import h5py

# Save in file

In [24]:
hdfFileName = '.pandas_hdf5_test.h5'
hdfFile = h5py.File(hdfFileName, mode='w')

hdfFile.attrs['explanation'] = 'Test file.'
hdfFile.attrs['sequence'] = np.arange(5)

numberOfColumns = 10_000
numberOfRows = 10_000
datasetShape = (numberOfRows, numberOfColumns)

trainGroup = hdfFile.create_group('train')

dataset = trainGroup.create_dataset('features', datasetShape, dtype=np.float_)

for row in range(numberOfRows):
    dataset[row,:] = np.random.rand(numberOfColumns)

In [25]:
hdfFile.close()

# Load from file

## Attributes and data it contains

In [26]:
hdfFile = h5py.File(hdfFileName, mode='r')

print('File attributes:')
print('{:20} {:20}'.format('Name', 'Value'))
for attribute in hdfFile.attrs.items():
    print('{:20} {}'.format(attribute[0], attribute[1]))

print('\nFile groups:')
print('{:20} {:20}'.format('Group name', 'Type'))
for group in hdfFile.items():
    print('{:20} {}'.format(group[0], group[1]))

hdfFile.close()

File attributes:
Name                 Value               
explanation          Test file.
sequence             [0 1 2 3 4]

File groups:
Group name           Type                
train                <HDF5 group "/train" (1 members)>


## Datasets

In [27]:
hdfFile = h5py.File(hdfFileName, mode='r')

dataset = hdfFile['/train/features']
numberOfRows, numberOfColumns = dataset.shape

for row in np.arange(numberOfRows):
    print(dataset[row, 1:5])

hdfFile.close()

[ 0.69771546  0.14065646  0.39935805  0.62964302]
[ 0.3888078   0.5237644   0.71608823  0.45056615]
[ 0.07057603  0.33511193  0.51311098  0.61494617]
[ 0.05034186  0.93861902  0.7491623   0.1172163 ]
[ 0.51180496  0.10339478  0.16746348  0.46500061]
[ 0.0831504   0.39540571  0.69175618  0.02243947]
[ 0.949526    0.11790291  0.59767392  0.5642723 ]
[ 0.44082474  0.94791161  0.71601726  0.86561949]
[ 0.10079865  0.99340722  0.82490017  0.43769406]
[ 0.70606565  0.4107522   0.55223529  0.35220148]
[ 0.75769985  0.50055915  0.29882317  0.97425572]
[ 0.31895875  0.31211802  0.41649593  0.5470633 ]
[ 0.25819805  0.45902385  0.54306565  0.35153831]
[ 0.97112034  0.03514487  0.74635648  0.68313607]
[ 0.12979476  0.89512011  0.69073803  0.84099756]
[ 0.66523309  0.59326793  0.28052502  0.53341255]
[ 0.34537736  0.6792716   0.79926009  0.72067737]
[ 0.25736081  0.52196185  0.07039873  0.4786629 ]
[ 0.66879152  0.14340199  0.54637164  0.54185038]
[ 0.98627008  0.75103948  0.33246543  0.35344821]


[ 0.97137764  0.23020184  0.49689635  0.15408154]
[ 0.08290083  0.50914916  0.45070848  0.32364872]
[ 0.1904858   0.26391955  0.86840769  0.94167533]
[ 0.62926239  0.12151884  0.80664977  0.67327054]
[ 0.63654207  0.306752    0.4450159   0.78203149]
[ 0.52385794  0.05834118  0.0075052   0.93868752]
[ 0.35988272  0.10310644  0.13557038  0.27079943]
[ 0.39326054  0.02575244  0.82421135  0.73051443]
[ 0.46312524  0.39253234  0.38183135  0.73000444]
[ 0.81998373  0.53817937  0.4835889   0.3723162 ]
[ 0.74178114  0.64424052  0.35478678  0.56037749]
[ 0.59646042  0.61340742  0.62259915  0.33564627]
[ 0.69116266  0.71095305  0.07605525  0.9750812 ]
[ 0.98193901  0.17215325  0.31300352  0.0741184 ]
[ 0.08081049  0.70279681  0.59647555  0.74810072]
[ 0.49877495  0.0489557   0.08858225  0.82861833]
[ 0.60945093  0.60472375  0.90994273  0.75646108]
[ 0.0594175   0.34615507  0.19614986  0.59646313]
[ 0.59554905  0.87119378  0.30071328  0.8655516 ]
[ 0.8732474   0.33713027  0.25222157  0.71407093]


[ 0.74387238  0.29828052  0.20136131  0.59131498]
[ 0.61254961  0.49331583  0.80821197  0.82265361]
[ 0.92348405  0.04113833  0.67306761  0.57695626]
[ 0.69399428  0.40386954  0.9094802   0.29895959]
[ 0.80763827  0.25061485  0.36958183  0.07521715]
[ 0.02850244  0.60106616  0.59613199  0.68716234]
[ 0.66494363  0.7595658   0.2622883   0.5306212 ]
[ 0.59373196  0.56857027  0.31598882  0.75018995]
[ 0.43664984  0.94213455  0.07015773  0.80654439]
[ 0.01315208  0.07572222  0.79412821  0.90844651]
[ 0.8446003   0.22300644  0.08486944  0.89040518]
[ 0.2680464   0.54656738  0.0008525   0.77274046]
[ 0.08223805  0.07635825  0.63038671  0.951384  ]
[ 0.52640134  0.34818898  0.6852125   0.15510219]
[ 0.20698421  0.8441292   0.28643698  0.79672846]
[ 0.67095689  0.84352661  0.28008418  0.95343291]
[ 0.4887685   0.64666002  0.3165307   0.39133132]
[ 0.63452051  0.39944516  0.67117157  0.52512165]
[ 0.01402506  0.94973727  0.98836953  0.3771146 ]
[ 0.68823425  0.96866044  0.83024127  0.54407744]


[ 0.94258112  0.33950946  0.18365736  0.9089272 ]
[ 0.67196516  0.7238813   0.4828805   0.85477517]
[ 0.13730492  0.77652219  0.75816339  0.89094478]
[ 0.04337378  0.03011725  0.54640489  0.06574158]
[ 0.81878368  0.83353612  0.92411716  0.13762631]
[ 0.73723205  0.29859798  0.37028447  0.19949445]
[ 0.53154195  0.5858897   0.84268854  0.54619952]
[ 0.74811474  0.17171976  0.33948348  0.17235262]
[ 0.21461392  0.54124494  0.94897043  0.06006467]
[ 0.74011717  0.21736701  0.79165176  0.50685683]
[ 0.11459576  0.52121159  0.05169587  0.44180139]
[ 0.27426702  0.73849208  0.50286307  0.61939264]
[ 0.69037781  0.20151625  0.64566662  0.12367821]
[ 0.95056279  0.91253359  0.08450957  0.10534226]
[ 0.31152933  0.25448914  0.00517583  0.156565  ]
[ 0.96056958  0.22913337  0.65889459  0.43427034]
[ 0.39327025  0.88163998  0.36390506  0.83577958]
[ 0.46738779  0.65292695  0.27376761  0.15965795]
[ 0.97024674  0.34504978  0.88084516  0.46971957]
[ 0.87718282  0.95976098  0.15930905  0.23412593]


[ 0.66976638  0.20608759  0.89756011  0.39967202]
[ 0.9994604   0.91367484  0.1092428   0.09244288]
[ 0.40314142  0.69266667  0.54835479  0.48801003]
[ 0.88337707  0.74134865  0.8101087   0.85402492]
[ 0.12078171  0.15267164  0.59019609  0.81342226]
[ 0.17534962  0.11299768  0.20924807  0.0580974 ]
[ 0.17442965  0.73618844  0.92824538  0.96530475]
[ 0.6307764   0.59190162  0.84222695  0.69919269]
[ 0.85042764  0.08930003  0.2041311   0.37776536]
[ 0.98270454  0.06053049  0.36120559  0.24932258]
[ 0.03804844  0.69221621  0.02598014  0.80003125]
[ 0.39400266  0.70888426  0.81574656  0.57787455]
[ 0.20589404  0.65410021  0.85075901  0.16750106]
[ 0.79164866  0.34467671  0.48784615  0.18449692]
[ 0.57698258  0.2524822   0.5744564   0.39557279]
[ 0.56698803  0.76776548  0.67488401  0.79406129]
[ 0.39608834  0.87366955  0.19787326  0.11619104]
[ 0.21248805  0.30174401  0.3091652   0.89181474]
[ 0.22479446  0.98208721  0.07317405  0.23391626]
[ 0.58049903  0.79024672  0.00442353  0.76146605]


[ 0.30515486  0.79285674  0.69547855  0.97200395]
[ 0.45446209  0.26118153  0.9748284   0.58919004]
[ 0.88152692  0.93792349  0.66001658  0.92578555]
[ 0.42499816  0.7198562   0.68303961  0.42599561]
[ 0.1108578   0.71532677  0.35952292  0.02251479]
[ 0.53741435  0.8969438   0.65647662  0.25973844]
[ 0.05789409  0.29670294  0.06509621  0.3425086 ]
[ 0.76867673  0.20498945  0.9547585   0.02074307]
[  3.44472590e-01   6.91379882e-04   7.10733729e-01   3.18126489e-01]
[ 0.08677374  0.85068588  0.57295593  0.82303637]
[ 0.05491127  0.12945176  0.84261348  0.71693597]
[ 0.31400539  0.475804    0.81499743  0.28629175]
[ 0.64093788  0.58997526  0.59440435  0.51511548]
[ 0.60437479  0.7002831   0.05179379  0.38042891]
[ 0.5943738   0.10089887  0.59667393  0.6977312 ]
[  9.53767852e-01   3.21039214e-01   2.92447490e-04   6.94707240e-01]
[ 0.09641566  0.57486159  0.50061971  0.11031762]
[ 0.87236882  0.36645393  0.98749339  0.58597127]
[ 0.84690108  0.64726987  0.31380074  0.31013152]
[ 0.783592

[ 0.66561099  0.7178653   0.18342473  0.77233726]
[ 0.79615872  0.35059796  0.18567357  0.09673388]
[ 0.04955964  0.3355612   0.74178126  0.62260215]
[ 0.90189022  0.78718697  0.72244451  0.1816647 ]
[ 0.18717814  0.65437806  0.81428543  0.45113125]
[ 0.60871121  0.57391564  0.58305186  0.99154676]
[ 0.62704381  0.21221285  0.70694092  0.81599081]
[ 0.17957497  0.11617342  0.44279463  0.2601061 ]
[ 0.99046718  0.53859372  0.64260291  0.88859456]
[ 0.64871661  0.89277202  0.07227299  0.61974398]
[ 0.70489108  0.41914263  0.73138974  0.67354476]
[ 0.82990782  0.75785163  0.51787223  0.52343491]
[ 0.39951645  0.12440843  0.76976395  0.85804109]
[ 0.19827191  0.99654886  0.96850359  0.00471498]
[ 0.20383768  0.82652678  0.74399254  0.27975614]
[ 0.42008784  0.58115863  0.29398267  0.72806794]
[ 0.18998695  0.54023048  0.20837217  0.3369759 ]
[ 0.9363323   0.63064521  0.31887601  0.52924195]
[ 0.88043901  0.62630008  0.40075454  0.3338226 ]
[ 0.11696631  0.99519415  0.80440921  0.33861734]


[ 0.5518069   0.31524284  0.7865979   0.55961426]
[ 0.89651796  0.15671671  0.09365785  0.26710711]
[  9.23540129e-01   7.69735324e-01   9.66896105e-01   8.18370072e-04]
[ 0.11997633  0.27704962  0.54588445  0.52591522]
[ 0.09278882  0.20731794  0.92227727  0.39039564]
[ 0.42391263  0.12764857  0.92941669  0.94746438]
[ 0.10355321  0.8866816   0.6481337   0.9661094 ]
[ 0.95552971  0.6328008   0.32293966  0.26748091]
[ 0.9276735   0.38975686  0.3582628   0.51512757]
[ 0.84686909  0.0574796   0.3833529   0.6238858 ]
[ 0.48317563  0.25683283  0.60230297  0.08754052]
[ 0.23951165  0.96896739  0.76258767  0.96508522]
[ 0.3286518   0.40173259  0.99177348  0.51170313]
[ 0.96619199  0.32502888  0.80672917  0.52578927]
[ 0.58111067  0.60539339  0.69396692  0.41471849]
[ 0.90357104  0.95001181  0.90237562  0.80633264]
[ 0.5823845   0.95653069  0.31582133  0.91333738]
[ 0.47788741  0.45397568  0.60411192  0.63580301]
[ 0.2014848   0.10228902  0.84116815  0.36310566]
[ 0.86351     0.53102627  0.07

[ 0.9839426   0.92121055  0.85121901  0.30836998]
[ 0.79542803  0.1031715   0.578245    0.99900445]
[ 0.69920062  0.22564678  0.72318789  0.36045898]
[ 0.6615849   0.07000631  0.29193531  0.81101345]
[ 0.64375981  0.78167256  0.13874342  0.58059032]
[ 0.66853532  0.88986814  0.62956811  0.6922124 ]
[ 0.34946893  0.13770322  0.97762509  0.07548657]
[ 0.9951961   0.17071322  0.06099405  0.67033193]
[ 0.19322385  0.47447427  0.36936082  0.95475917]
[ 0.8212573   0.44434601  0.75381795  0.59846533]
[ 0.69114533  0.37910662  0.91556322  0.52234518]
[ 0.32148942  0.88578338  0.3622291   0.97271228]
[ 0.10448214  0.62811611  0.54572346  0.44728358]
[ 0.58756655  0.56666919  0.46954235  0.64564419]
[ 0.76244025  0.73725196  0.69587424  0.23104474]
[ 0.77170095  0.49635218  0.19793675  0.57674764]
[ 0.19240766  0.90280174  0.84260716  0.76371116]
[ 0.38176953  0.70702006  0.23969361  0.44470081]
[ 0.35585512  0.82001237  0.76228127  0.09886795]
[ 0.54330837  0.12098864  0.242877    0.23573223]


In [28]:
os.remove(hdfFileName)