In [188]:
import numpy
import scipy.linalg
import time

In [7]:
matrix = numpy.diag([3, 4, 8, -1])
print(matrix, '\n')
print(scipy.linalg.inv(matrix))

[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  8  0]
 [ 0  0  0 -1]] 

[[ 0.33333333  0.         -0.          0.        ]
 [ 0.          0.25       -0.          0.        ]
 [ 0.          0.          0.125       0.        ]
 [ 0.          0.          0.         -1.        ]]


In [25]:
size = 100
matrix = 2*numpy.eye(size) + numpy.diag(-numpy.ones(size-1), 1) + numpy.diag(-numpy.ones(size-1), -1)
independent = numpy.zeros((size,1)); independent[0] = 1; independent[-1] = 1
solution = scipy.linalg.solve(matrix, independent)
print('error = {:e}'.format(scipy.linalg.norm(matrix@solution-independent)))
solution = scipy.linalg.solve(matrix, independent, assume_a='sym')
print('error = {:e}'.format(scipy.linalg.norm(matrix@solution-independent)))
solution = scipy.linalg.inv(matrix) @ independent
print('error = {:e}'.format(scipy.linalg.norm(matrix@solution-independent)))

error = 1.299483e-15
error = 1.260971e-15
error = 6.260713e-15


In [183]:
size = 300
matrix = numpy.random.rand(2*size,size)
independent = numpy.random.rand(2*size,1)
leastSquareSolution, error, _, _ = scipy.linalg.lstsq(matrix, independent)
print('log(error) = {:f}'.format(numpy.log10(error[0])))

log(error) = 1.379474


In [186]:
matrix = numpy.array([
        [1, -3, 3],
        [3, -5, 3],
        [6, -6, 4]
    ])
correctEigenValues = numpy.array([4, -2, -2])
correctEigenVectors = numpy.array([
        [0.5, 1.0, -1.0],
        [0.5, 0.0,  1.0],
        [1.0, 1.0,  0.0]
    ]) # eigen vectors at columns
values, lVectors, rVectors = scipy.linalg.eig(matrix, left=True, right=True)
print(values, '\n')
print(lVectors, '\n')
print(rVectors, '\n')
print(correctEigenValues, '\n')
print(correctEigenVectors, '\n')

[ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j] 

[[-0.57735027+0.j         -0.18732647+0.43309598j -0.18732647-0.43309598j]
 [ 0.57735027+0.j          0.79821513+0.j          0.79821513-0.j        ]
 [-0.57735027+0.j         -0.30544433-0.21654799j -0.30544433+0.21654799j]] 

[[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]] 

[ 4 -2 -2] 

[[ 0.5  1.  -1. ]
 [ 0.5  0.   1. ]
 [ 1.   1.   0. ]] 



In [191]:
size = 10_000
matrix = numpy.random.rand(size,size)
independent=numpy.random.rand(size,1)

start = time.time(); lu, piv = scipy.linalg.lu_factor(matrix); end = time.time()
print('decomposition time:   {:f}'.format(end-start))

start = time.time(); _ = scipy.linalg.solve(matrix, independent); end = time.time()
print('"solve" elapsed time: {:f}'.format(end-start))

start = time.time(); _ = scipy.linalg.lu_solve((lu,piv), independent); end = time.time()
print('"lu" elapsed time:    {:f}'.format(end-start))

decomposition time:   72.770669
"solve" elapsed time: 90.627357
"lu" elapsed time:    0.471891
